[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "zlib", "libjpeg", "libpng", "freetype", "postgresql", "postgresql.dev"]

[phases.install]
cmds = ["pip install --only-binary=:all: --no-cache-dir -r requirements.txt"]

[start]
cmd = "python app.py" 